### ISSUE TITLE
Missing range checking (panic: runtime error: index out of range)

### ISSUE THREAD

**Issue by sam-kamerer** [isacikgoz/gitbatch#87]
https://github.com/isacikgoz/gitbatch/blob/a5e4ed9b5ba5273667c0f8abcce74c14dcd0db67/gui/dynamicview.go#L62

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/isacikgoz/gitbatch/gui.(*Gui).commitStats(0xc00013cfa0, 0x1, 0xc0002785a0, 0x0)
	/home/isacikgoz/go/src/github.com/isacikgoz/gitbatch/gui/dynamicview.go:62 +0x4e9
github.com/isacikgoz/gitbatch/gui.(*Gui).commitCursorUp(0xc00013cfa0, 0xc000218000, 0xc0002785a0, 0x28, 0x5)
	/home/isacikgoz/go/src/github.com/isacikgoz/gitbatch/gui/focusviews.go:50 +0xba
github.com/isacikgoz/gitbatch/gui.(*Gui).commitCursorUp-fm(0xc000218000, 0xc0002785a0, 0x7, 0xc000000301)
	/home/isacikgoz/go/src/github.com/isacikgoz/gitbatch/gui/keybindings.go:417 +0x3e
github.com/jroimartin/gocui.(*Gui).execKeybindings(0xc000218000, 0xc0002785a0, 0xc016347b88, 0x14676b8, 0x0, 0x0)
	/home/isacikgoz/go/src/github.com/jroimartin/gocui/gui.go:629 +0xbe
github.com/jroimartin/gocui.(*Gui).onKey(0xc000218000, 0xc016347b88, 0xc0045d60a0, 0xc000220010)
	/home/isacikgoz/go/src/github.com/jroimartin/gocui/gui.go:593 +0x1b0
github.com/jroimartin/gocui.(*Gui).handleEvent(0xc000218000, 0xc016347b88, 0x2, 0x0)
	/home/isacikgoz/go/src/github.com/jroimartin/gocui/gui.go:413 +0x40
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc000218000, 0xc000218000, 0x0)
	/home/isacikgoz/go/src/github.com/jroimartin/gocui/gui.go:373 +0x2c3
github.com/isacikgoz/gitbatch/gui.(*Gui).Run(0xc00013cfa0, 0x0, 0x0)
	/home/isacikgoz/go/src/github.com/isacikgoz/gitbatch/gui/gui.go:140 +0x1e3
main.run(0x0, 0x0, 0x0, 0x172704f, 0x5, 0x0, 0xc0000e4500, 0x0, 0x0, 0x0, ...)
	/home/isacikgoz/git/gitbatch/main.go:52 +0x122
main.main()
	/home/isacikgoz/git/gitbatch/main.go:24 +0xc2
```

**Comment by isacikgoz** [comment]
Hey @sam-kamerer , thanks for the feedback I will be looking into this.

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.
